# Generated by Django 4.2.4 on 2023-10-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rno', models.IntegerField()),
                ('p', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Data Science'), (3, 'Data Analysis'), (4, 'Java')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='details',
            field=models.CharField(max_length=1000, verbose_name='Blog Details'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published On'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Blog Title'),
        ),
    ]
